name: also_migrate
version: 0.3.5
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/also_migrate
summary: Migrate multiple tables with similar schema at once.
description: Migrate multiple tables with similar schema at once.
dependencies: null
development_dependencies:
  - rake
  - rspec